# Generated by Django 3.2.4 on 2022-11-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('webwsite', models.URLField(max_length=100)),
                ('foundation', models.PositiveBigIntegerField()),
            ],
        ),
    ]
